// Associated system call numbers
#define SYS_fork              1
#define SYS_exit              2
#define SYS_wait              3
#define SYS_pipe              4
#define SYS_read              5
#define SYS_kill              6
#define SYS_exec              7
#define SYS_fstat             8
#define SYS_chdir             9
#define SYS_dup              10
#define SYS_getpid           11
#define SYS_sbrk             12
#define SYS_sleep            13
#define SYS_uptime           14
#define SYS_open             15
#define SYS_write            16
#define SYS_mknod            17
#define SYS_unlink           18
#define SYS_link             19
#define SYS_mkdir            20
#define SYS_close            21
#define SYS_getname          22
#define SYS_setname          23
#define SYS_getmaxproc       24
#define SYS_setmaxproc       25
#define SYS_setvc		     34
#define SYS_getcwd           38
#define SYS_tostring         39
#define SYS_getpath          43
#define SYS_setpath          44
#define SYS_ps               45
#define SYS_fork2 			 54
#define SYS_setalive		 55
#define SYS_getnumcontainers 56
#define SYS_setroot      	 62
#define SYS_getcid      	 63
#define SYS_get_con_shm      64
#define SYS_get_new_cid      65
#define SYS_print            66
#define SYS_get_proc_pipe    67


#define SYS_mutex_create 	 72
#define SYS_mutex_delete 	 73
#define SYS_mutex_lock 		 74
#define SYS_mutex_unlock 	 75
#define SYS_cv_wait 		 76
#define SYS_cv_signal 		 77
#define SYS_shm_get 		 78
#define SYS_shm_rem 		 79
#define SYS_mutex_get        80

#define SYS_prio_set 		 92
#define SYS_test_0 			 93
#define SYS_test_1 			 94
#define SYS_test_2 			 95
#define SYS_remove_node 	 96
